name: Autorelease Cos
on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: install
        run: |
          sudo pip install coscmd
          sudo yarn install
          sudo yarn build

      - name: configs
        env:
          SECRET_ID: ${{ secrets.TCLOUD_API_ID }}
          SECRET_KEY: ${{ secrets.TCLOUD_API_KEY }}
          BUCKET: excalidraw-cn-1251014631
          REGION: ap-nanjing
        run: |
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: upload
        run: |
          coscmd upload -rfs --delete ./build/ /
